/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DanhMucIndexRouteImport } from './routes/danh-muc.index'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'
import { Route as DanhMucSlugRouteImport } from './routes/danh-muc.$slug'

const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhMucIndexRoute = DanhMucIndexRouteImport.update({
  id: '/danh-muc/',
  path: '/danh-muc/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhMucSlugRoute = DanhMucSlugRouteImport.update({
  id: '/danh-muc/$slug',
  path: '/danh-muc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/danh-muc/': typeof DanhMucIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/danh-muc': typeof DanhMucIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/danh-muc/': typeof DanhMucIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/thanh-toan'
    | '/danh-muc/$slug'
    | '/san-pham/$slug'
    | '/danh-muc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/thanh-toan'
    | '/danh-muc/$slug'
    | '/san-pham/$slug'
    | '/danh-muc'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/lien-he'
    | '/thanh-toan'
    | '/danh-muc/$slug'
    | '/san-pham/$slug'
    | '/danh-muc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  GioHangRoute: typeof GioHangRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  ThanhToanRoute: typeof ThanhToanRoute
  DanhMucSlugRoute: typeof DanhMucSlugRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
  DanhMucIndexRoute: typeof DanhMucIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-muc/': {
      id: '/danh-muc/'
      path: '/danh-muc'
      fullPath: '/danh-muc/'
      preLoaderRoute: typeof DanhMucIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-muc/$slug': {
      id: '/danh-muc/$slug'
      path: '/danh-muc/$slug'
      fullPath: '/danh-muc/$slug'
      preLoaderRoute: typeof DanhMucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  GioHangRoute: GioHangRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  ThanhToanRoute: ThanhToanRoute,
  DanhMucSlugRoute: DanhMucSlugRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
  DanhMucIndexRoute: DanhMucIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
