/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DanhMucIndexRouteImport } from './routes/danh-muc.index'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'
import { Route as DanhMucSlugRouteImport } from './routes/danh-muc.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhMucIndexRoute = DanhMucIndexRouteImport.update({
  id: '/danh-muc/',
  path: '/danh-muc/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhMucSlugRoute = DanhMucSlugRouteImport.update({
  id: '/danh-muc/$slug',
  path: '/danh-muc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/danh-muc/': typeof DanhMucIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/danh-muc': typeof DanhMucIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
  '/danh-muc/': typeof DanhMucIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/danh-muc/$slug' | '/san-pham/$slug' | '/danh-muc/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/danh-muc/$slug' | '/san-pham/$slug' | '/danh-muc'
  id: '__root__' | '/' | '/danh-muc/$slug' | '/san-pham/$slug' | '/danh-muc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DanhMucSlugRoute: typeof DanhMucSlugRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
  DanhMucIndexRoute: typeof DanhMucIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-muc/': {
      id: '/danh-muc/'
      path: '/danh-muc'
      fullPath: '/danh-muc/'
      preLoaderRoute: typeof DanhMucIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-muc/$slug': {
      id: '/danh-muc/$slug'
      path: '/danh-muc/$slug'
      fullPath: '/danh-muc/$slug'
      preLoaderRoute: typeof DanhMucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DanhMucSlugRoute: DanhMucSlugRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
  DanhMucIndexRoute: DanhMucIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
